const OK=200;
const CREATED=201;
const BAD_REQUEST=400;
const UNAUTHORIZED=401;
const FORBIDDEN=403;
const NOT_FOUND=404;
const INTERNAL_SERVER_ERROR=500;
const T00_MANY_REQUESTS=429;
const CONFLICT=409;
const UNPROCESSABLE_CONTENT=422;

module.exports = {OK, CREATED, BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND, INTERNAL_SERVER_ERROR, T00_MANY_REQUESTS, CONFLICT, UNPROCESSABLE_CONTENT};